title: DevCastBrasil
email: oi@felquis.com
description: ""

baseurl: "/"
url: "http://devcast.github.io"

# paginate
paginate: 5
paginate_path: /page/:num

# permalink
permalink: :title

# sass
sass:
    style: :compressed

# Build settings
markdown: kramdown
