title: "The Official DevCastBrasil Blog"
email: oi@felquis.com
description: "The next generation HTML5 hybrid app development SDK"

baseurl: "/"
url: "http://devcast.github.io"

# paginate
paginate: 5
paginate_path: /page/:num

# permalink
permalink: :title

# sass
sass:
    style: :compressed

# Build settings
markdown: kramdown

authors:
  randsonjs:
    name: "Randson Oliveira"
    username: randsonjs
    avatar: c66919cb194f96c696c1da0c47354a6a
    email: randsonjs@gmail.com
  felquis:
    name: "Felquis Gimenes"
    username: felquis
    avatar: c66919cb194f96c696c1da0c47354a6a
    email: oi@felquis.com