title: "The Official DevCastBrazil Blog"
email: oi@felquis.com
description: "The next generation blog about development"

baseurl: "/"
url: "http://devcast.github.io"

# paginate
paginate: 5
paginate_path: /page/:num

# permalink
permalink: :title

# sass
sass:
    style: :compressed

# Build settings
markdown: kramdown

authors:
  randsonjs:
    name:     Randson Oliveira
    username: randsonjs
    url:      https://twitter.com/randsonjs
    email:    randsonjs@gmail.com
    avatar:   4191734
  felquis:
    name:     Felquis Gimenes
    username: felquis
    url:      https://twitter.com/felquis
    email:    oi@felquis.com
    avatar:   736728